services:
  # PostgreSQL 데이터베이스
  postgres:
    image: postgres:15
    container_name: fs_master_postgres
    environment:
      POSTGRES_DB: fs_master_web
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fs_master_network
    restart: unless-stopped

  # Redis (스케줄링 및 캐싱용)
  redis:
    image: redis:7-alpine
    container_name: fs_master_redis
    ports:
      - "6379:6379"
    networks:
      - fs_master_network
    restart: unless-stopped

  # FS Master 웹 애플리케이션
  web:
    build: .
    container_name: fs_master_web
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/fs_master_web
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "5000:5000"
    volumes:
      - ./app.py:/app/app.py
      - ./db_connection_test:/app/db_connection_test
      - ./templates:/app/templates
      - ./logs:/app/logs
    depends_on:
      - postgres
      - redis
    networks:
      - fs_master_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  fs_master_network:
    driver: bridge 