services:
  # SSH 서버
  ssh:
    image: linuxserver/openssh-server:latest
    container_name: data_sync_ssh_server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Seoul
      - USER_NAME=developer
      - USER_PASSWORD=password123
      - SUDO_ACCESS=true
      - PASSWORD_ACCESS=true
    ports:
      - "22:2222"
    volumes:
      - .:/workspace
      - ssh_config:/config
    restart: unless-stopped

volumes:
  ssh_config: 