version: '3.8'
services:
  # PostgreSQL 데이터베이스
  postgres:
    image: postgres:13
    container_name: data-sync-postgres-wsl
    environment:
      POSTGRES_DB: fs_master_web
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: infomax
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - wsl-network
    restart: unless-stopped

  # Redis 캐시
  redis:
    image: redis:6-alpine
    container_name: data-sync-redis-wsl
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - wsl-network
    restart: unless-stopped

  # 웹 애플리케이션 (WSL 최적화)
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: data-sync-web-wsl
    ports:
      - "5000:5000"
    volumes:
      # WSL 경로 최적화
      - ../src:/app/src
      - ../templates:/app/templates
      - ../tools:/app/tools
      - ../requirements.txt:/app/requirements.txt
    environment:
      - DATABASE_URL=postgresql://postgres:infomax@postgres:5432/fs_master_web
      - REDIS_URL=redis://redis:6379/0
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONPATH=/app
    depends_on:
      - postgres
      - redis
    networks:
      - wsl-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  wsl-network:
    driver: bridge 